CREATE TABLE [dbo].[tbl_PostRequirment] (
    [PostRequirmentID] UNIQUEIDENTIFIER DEFAULT (newid()) NULL,
    [RegistrationID]   UNIQUEIDENTIFIER NULL,
    [PropertyType]     NUMERIC (18)     NOT NULL,
    [City]             NUMERIC (18)     NOT NULL,
    [CityOther]        VARCHAR (100)    NULL,
    [Locality]         VARCHAR (500)    NOT NULL,
    [RequiredArea]     NUMERIC (18)     NOT NULL,
    [TransactionType]  NUMERIC (18)     NOT NULL,
    [Amenities]        VARCHAR (MAX)    NULL,
    [MinimumPrice]     NUMERIC (18)     NOT NULL,
    [maximumPrice]     NUMERIC (18)     NOT NULL,
    [BHK]              VARCHAR (MAX)    NULL,
    [AgeConstruction]  NUMERIC (18)     NULL,
    [ClientName]       VARCHAR (100)    NULL,
    [ClientEmail]      VARCHAR (100)    NULL,
    [ClientAddress]    VARCHAR (500)    NULL,
    [ClientAddress2]   VARCHAR (500)    NULL,
    [ClientAddress3]   VARCHAR (500)    NULL,
    [ClientMobile]     VARCHAR (20)     NULL,
    [ClientState]      NUMERIC (18)     NULL,
    [ClientCity]       NUMERIC (18)     NULL,
    [ClientCityOther]  VARCHAR (100)    NULL,
    [ClientPinCode]    VARCHAR (20)     NULL,
    [CreatedDate]      DATETIME         DEFAULT (getdate()) NOT NULL,
    [CreatedBy]        NUMERIC (18)     NULL,
    [Enabled]          BIT              DEFAULT ((1)) NOT NULL
);

