CREATE TABLE [dbo].[tbl_Property] (
    [PropertyID]           UNIQUEIDENTIFIER CONSTRAINT [DF_tbl_Property_PropertyID_1] DEFAULT (newid()) NOT NULL,
    [PropertyNumberSeries] NUMERIC (18)     IDENTITY (100001, 1) NOT NULL,
    [PropertyCode]         VARCHAR (50)     CONSTRAINT [DF_tbl_Property_PropertyCode] DEFAULT ('HOME') NOT NULL,
    [RegistrationID]       UNIQUEIDENTIFIER NULL,
    [TransactionType]      INT              NOT NULL,
    [OwnershipType]        INT              NOT NULL,
    [SubPropertyType]      INT              NOT NULL,
    [PropertyCity]         INT              NOT NULL,
    [PropertyOtherCity]    VARCHAR (50)     NULL,
    [Locality]             VARCHAR (100)    NOT NULL,
    [Area]                 INT              NOT NULL,
    [Measure]              VARCHAR (50)     NULL,
    [Rent]                 INT              NOT NULL,
    [SocietyName]          VARCHAR (50)     NULL,
    [Bedroom]              VARCHAR (50)     NOT NULL,
    [Floor]                INT              NOT NULL,
    [Description]          VARCHAR (500)    NOT NULL,
    [Availability]         INT              NULL,
    [Bathroom]             VARCHAR (50)     NOT NULL,
    [Balcony]              VARCHAR (50)     NULL,
    [FloorInBuilding]      VARCHAR (50)     NOT NULL,
    [Furnished]            INT              NOT NULL,
    [Facing]               INT              NOT NULL,
    [Amenities]            VARCHAR (MAX)    NULL,
    [ShoppingMallDistance] INT              NOT NULL,
    [HospitalDistance]     INT              NOT NULL,
    [SchoolDistance]       INT              NOT NULL,
    [ATMDistance]          INT              NOT NULL,
    [OwnerName]            NVARCHAR (50)    NOT NULL,
    [OwnerCity]            INT              NOT NULL,
    [OwnerOtherCity]       VARCHAR (50)     NULL,
    [OwnerAddress]         VARCHAR (500)    NOT NULL,
    [Mobile]               VARCHAR (15)     NOT NULL,
    [AlternateNumber]      VARCHAR (15)     NULL,
    [EmailID]              VARCHAR (50)     NOT NULL,
    [Verified]             BIT              CONSTRAINT [DF_tbl_Property_Verified] DEFAULT ((0)) NOT NULL,
    [Rented]               BIT              CONSTRAINT [DF_tbl_Property_Rented] DEFAULT ((0)) NOT NULL,
    [HotProperty]          BIT              CONSTRAINT [DF_tbl_Property_HotProperty] DEFAULT ((0)) NOT NULL,
    [Enabled]              BIT              CONSTRAINT [DF_tbl_Property_Enabled] DEFAULT ((1)) NOT NULL,
    [CreateDate]           DATETIME         CONSTRAINT [DF_tbl_Property_CreateDate_1] DEFAULT (getdate()) NOT NULL,
    [RegiesterdFrom]       VARCHAR (10)     NULL,
    [OwnerState]           INT              NULL,
    [OwnerAddress2]        VARCHAR (500)    NULL,
    [OwnerAddress3]        VARCHAR (500)    NULL,
    [OwnerPinCode]         VARCHAR (20)     NULL,
    CONSTRAINT [PK_tbl_Property_1] PRIMARY KEY CLUSTERED ([PropertyCode] ASC)
);

