//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homely.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Master_Amenities
    {
        public decimal AmenityId { get; set; }
        public string Amenity { get; set; }
        public string ImagePath { get; set; }
        public string BigImagePath { get; set; }
        public string BigImageHoverPath { get; set; }
        public bool Enabled { get; set; }
        public decimal Order { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ImageHoverPath { get; set; }
    }
}
