//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homely.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuickListing
    {
        public System.Guid ListingID { get; set; }
        public Nullable<System.Guid> RegistrationID { get; set; }
        public string ContactFor { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public bool Enabled { get; set; }
    }
}
