//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homely.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Master_SubPropertyType
    {
        public decimal SubPropertyTypeID { get; set; }
        public int PropertyTypeID { get; set; }
        public string SubPropertyType { get; set; }
        public bool Enabled { get; set; }
        public decimal Order { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
