//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homely.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Property1
    {
        public System.Guid PropertyID { get; set; }
        public decimal PropertyNumberSeries { get; set; }
        public string PropertyCode { get; set; }
        public Nullable<System.Guid> RegistrationID { get; set; }
        public int TransactionType { get; set; }
        public int OwnershipType { get; set; }
        public int SubPropertyType { get; set; }
        public int PropertyCity { get; set; }
        public string PropertyOtherCity { get; set; }
        public string Locality { get; set; }
        public int Area { get; set; }
        public string Measure { get; set; }
        public int Rent { get; set; }
        public string SocietyName { get; set; }
        public string Bedroom { get; set; }
        public int Floor { get; set; }
        public string Description { get; set; }
        public Nullable<int> Availability { get; set; }
        public string Bathroom { get; set; }
        public string Balcony { get; set; }
        public string FloorInBuilding { get; set; }
        public int Furnished { get; set; }
        public int Facing { get; set; }
        public string Amenities { get; set; }
        public int ShoppingMallDistance { get; set; }
        public int HospitalDistance { get; set; }
        public int SchoolDistance { get; set; }
        public int ATMDistance { get; set; }
        public string OwnerName { get; set; }
        public int OwnerCity { get; set; }
        public string OwnerOtherCity { get; set; }
        public string OwnerAddress { get; set; }
        public string Mobile { get; set; }
        public string AlternateNumber { get; set; }
        public string EmailID { get; set; }
        public bool Verified { get; set; }
        public bool Rented { get; set; }
        public bool HotProperty { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string RegiesterdFrom { get; set; }
        public Nullable<int> OwnerState { get; set; }
        public string OwnerAddress2 { get; set; }
        public string OwnerAddress3 { get; set; }
        public string OwnerPinCode { get; set; }
        public Nullable<int> TimeSlot { get; set; }
        public string AnyOtherTime { get; set; }
        public string slugUrl { get; set; }
        public Nullable<int> LocalityId { get; set; }
        public string suitable { get; set; }
        public string securityDeposit { get; set; }
        public string maintenanceCharge { get; set; }
        public string restriction { get; set; }
        public string minimumContract { get; set; }
    }
}
