//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homely.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostRequirment
    {
        public System.Guid PostRequirmentID { get; set; }
        public Nullable<System.Guid> RegistrationID { get; set; }
        public decimal PropertyType { get; set; }
        public decimal City { get; set; }
        public string CityOther { get; set; }
        public string Locality { get; set; }
        public decimal RequiredArea { get; set; }
        public decimal TransactionType { get; set; }
        public string Amenities { get; set; }
        public decimal MinimumPrice { get; set; }
        public decimal maximumPrice { get; set; }
        public string BHK { get; set; }
        public Nullable<decimal> AgeConstruction { get; set; }
        public string ClientName { get; set; }
        public string ClientEmail { get; set; }
        public string ClientAddress { get; set; }
        public string ClientAddress2 { get; set; }
        public string ClientAddress3 { get; set; }
        public string ClientMobile { get; set; }
        public Nullable<decimal> ClientState { get; set; }
        public Nullable<decimal> ClientCity { get; set; }
        public string ClientCityOther { get; set; }
        public string ClientPinCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public bool Enabled { get; set; }
    }
}
