//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homely.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PropertyReview
    {
        public System.Guid ReviewID { get; set; }
        public Nullable<System.Guid> RegistrationID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public string Review { get; set; }
        public Nullable<bool> HomePage { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Enabled { get; set; }
        public Nullable<decimal> OwnershipType { get; set; }
        public string ReviewFor { get; set; }
        public string ReviewForValue { get; set; }
        public string RatingLocation1 { get; set; }
        public string RatingLocation2 { get; set; }
        public string RatingLocation3 { get; set; }
        public string RatingLocation4 { get; set; }
        public string RatingLocation5 { get; set; }
        public string RatingLocation6 { get; set; }
        public string RatingSociety1 { get; set; }
        public string RatingSociety2 { get; set; }
        public string RatingSociety3 { get; set; }
        public string RatingSociety4 { get; set; }
        public string RatingSociety5 { get; set; }
        public string RatingSociety6 { get; set; }
        public string RatingSociety7 { get; set; }
        public Nullable<bool> Approved { get; set; }
    }
}
