//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homely.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Registration
    {
        public System.Guid RegistrationID { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public decimal OwnershipType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Alternate { get; set; }
        public decimal City { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyName { get; set; }
        public string PropertyType { get; set; }
        public string DealsIn { get; set; }
        public string SpecialiseIn { get; set; }
        public string PropertiesAt { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public bool Enabled { get; set; }
        public string PermanentAddress { get; set; }
        public string Image { get; set; }
    }
}
