//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homely.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FavouriteProperty
    {
        public System.Guid FavoriteId { get; set; }
        public System.Guid RegistrationId { get; set; }
        public string PropertyCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Deleted { get; set; }
    }
}
